/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hw2.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include <dirent.h>
#include <time.h>

void do_delete(char *host, char *filename);
void do_rename(char *host, char *filename, char *str);
void do_save(char *host, char *filename, char *str);
void do_head(char *host, char *filename, int head_len);
void do_tree(char *host);
int check_strLen(const char *str, int max);
int check_inputnum(const char *input);
void timedl(void);

int
main (int argc, char *argv[])
{
	char *host;
	char *filename;
	char *str;
	int sign = 0;
	int head_len = 0;

	if (argc < 3) {
		printf ("Usage: %s host [operation] [filename] [string | length]\n", argv[0]);
		exit (1);
	}
	else
	{   if (!strcmp(argv[2], "head"))
	    {   if (argc != 5) {
		        printf("Usage: %s host head [filename] [length]\n", argv[0]);
		        return 0;
	        }
            sign = 1;
            host = argv[1];
	        filename = argv[3];

	        if (!check_strLen(filename, MAXFILENAME)) 
		        return 0;
	        if (!check_inputnum(argv[4]))
		        return 0;
	        head_len = atoi(argv[4]);
        }   
        
        else if (!strcmp(argv[2], "delete")) {
	        if (argc != 4) {
		        printf("Usage: %s host delete [filename]\n", argv[0]);
		        return 0;
	        }

            sign = 2;
            host = argv[1];
            filename = argv[3];
            if (!check_strLen(filename, MAXFILENAME)) 
		        return 0;
        }
	
	    else if (!strcmp(argv[2], "save")) {
	        if (argc != 5) {
		        printf("Usge: %s host save [filename] [string]\n", argv[0]);
		        return 0;
	        }

            sign = 3;
            host = argv[1];
            filename = argv[3];
            str = argv[4];
            if (!check_strLen(filename, MAXFILENAME)) 
		        return 0;
	        if (!check_strLen(str, MAXSTRLEN)) 
		        return 0;
	    }
	    
	    else if (!strcmp(argv[2], "rename")){
	        if (argc != 5) {
		        printf("Usage: %s host rename [old_filename] [new_filename]\n", argv[0]);
		        return 0;
	        }

            sign = 4;
            host = argv[1];
            filename = argv[3];
            str = argv[4];
            if (!check_strLen(filename, MAXFILENAME)) 
		        return 0;
	        if (!check_strLen(str, MAXSTRLEN)) 
		        return 0;
        }
        
        else if (!strcmp(argv[2], "tree"))
        {   if (argc != 3)
            {   printf("Usage: %s host tree\n", argv[0]);
                return 0;
            }
            sign = 5;
            host = argv[1];        
        }
        
        else {
            printf("Command %s is not supportted.\n", argv[2]);
            printf("Please try head, delete, save, rename, tree.\n");
            return 0;
        }
	}
	
	switch (sign) {
	    case 1: do_head(host, filename, head_len); break;
	    case 2: do_delete(host, filename);         break;
	    case 3: do_save(host, filename, str);      break;
	    case 4: do_rename(host, filename, str);    break;
	    case 5: do_tree(host);                     break;
	    default: printf("exiting...\n");     return 0; //impossible value
    }
	
	//hwprog_1 (host);
exit (0);
}

void do_tree(char *host)
{
	CLIENT *clnt;
	str  *result_5;
	char *treedl_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HWPROG, HWVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_5 = treedl_1((void*)&treedl_1_arg, clnt);
	if (result_5 == (str *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("%s\n", *result_5);
	
	printf("done.\n");
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}



void do_head(char *host, char *filename, int head_len)
{
    CLIENT *clnt;
	str  *result_4;
	stringInt  headdl_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HWPROG, HWVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    headdl_1_arg.filename = filename;
    headdl_1_arg.len = head_len;
	
	result_4 = headdl_1(&headdl_1_arg, clnt);
	if (result_4 == (str *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if (!strcmp(*result_4, "2"))
	{
	    timedl();
	    printf("head %s %d\n", filename, head_len);
	    printf("File %s has been created.\n", filename);
	}
	else
	{
	    printf("%s\n", *result_4);
	    printf("done\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

}

void do_save(char *host, char *filename, char *str)
{
	CLIENT *clnt;
	int  *result_3;
	stringPair  savedl_1_arg;
	
#ifndef	DEBUG
	clnt = clnt_create (host, HWPROG, HWVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    
    savedl_1_arg.filename = filename;
    savedl_1_arg.str = str;

	result_3 = savedl_1(&savedl_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}	
	else if (*result_3 == -1)
	    printf("File %s does not exist.\n", filename);
    else
    {   timedl();
        printf("save %s %s\n", filename, str);
        printf("%d bytes of data have been written to the file %s.\n", *result_3, filename);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void do_rename(char *host, char *filename, char *str)
{
	CLIENT *clnt;
	int  *result_2;
	stringPair  renamedl_1_arg;
	

#ifndef	DEBUG
	clnt = clnt_create (host, HWPROG, HWVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    renamedl_1_arg.filename = filename;
    renamedl_1_arg.str = str;

	result_2 = renamedl_1(&renamedl_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	timedl();
	printf("rename %s %s\n", filename, str);
	printf("File %s has been renamed to %s.\n", filename, str);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void do_delete(char *host, char *filename)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, HWPROG, HWVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = deletedl_1(&filename, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if (*result_1 == 2)
        printf("File %s does not exist.\n", filename);
    else
    {
        timedl();
        printf("delete %s\n", filename);
        printf("File %s has been deleted.\n", filename);
    }    
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int check_inputnum(const char *input) {
    int i;

    for (i = 0; input[i] != '\0'; i++) {
	    if (!isdigit(input[i])) {
	        printf("ERROR: %s should be all digit.\n", input);
	        return 0;
	    }
    }

    return 1;
}

 
int check_strLen(const char *str, int max)
{   if (strlen(str) >= max) {
        printf("ERROR: file %s is too long.\n", str);
        printf("The maximum filename is 15.\n");
        printf("The maximum string is 511.\n");
	    return 0;
    }
            
    return 1;
}
        

void timedl(void)
{
    time_t t;
	struct tm *tminfo;
   
	time(&t);
	tminfo = localtime(&t);
	tminfo->tm_mon += 1;
	printf("[%d/%d %d:%d:%d] ", tminfo->tm_mon, tminfo->tm_mday, tminfo->tm_hour, tminfo->tm_min, tminfo->tm_sec);
}

